### PR TITLE
changing record nsamp removes projectors

### LINKED ISSUE #53: projectors should be removed when number of samples in a record changes
Otherwise dastard will panic when it tries to use projectors on a record of the wrong length.

Dastard already checks that the projectors length matches the number of samples when setting projectors.

### PR DESCRIPTION
**Pull request by ggggggggg**
fixes #53

### CODE REVIEW

File: data_source.go [hunk 1]
```diff
@@ -45,8 +45,8 @@ type DataSource interface {
 
 // ConfigureMixFraction provides a default implementation for all non-lancero sources that
 // don't need the mix
-func (ds *AnySource) ConfigureMixFraction(channelIndexex int, mixFraction float64) error {
```
Comment (ggggggggg) [inline data_source.go]: What you don't like indexex?
